[package]
name = "rinklers"
version = "0.1.0"
authors = ["Alex Mikhalev <alexmikhalevalex@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
signal = "0.3"
# chrono = "0.2"
chrono = { git = "https://github.com/amikhalev/rust-chrono.git", branch = "weekday-derive-hash" }
